# Generated by Django 4.1.1 on 2022-10-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_CB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reserva',
            new_name='reserva_1',
        ),
    ]
