# Generated by Django 4.1.1 on 2022-10-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_CB', '0002_rename_reserva_reserva_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='varios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe_nom', models.CharField(max_length=60)),
                ('Importe_num', models.IntegerField()),
                ('Fecha_importe', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='reserva_1',
        ),
    ]
